// Límites alineados con las restricciones @Size del backend.
export const LIMITES = {
  TITULO_PROYECTO_MAX: 100,
  ITEM_CONTENIDO_MAX: 7000,
  ESTADO_EVALUACION_ID_MAX: 50,
  ESTUDIANTES_MAX: 3,
  USUARIO_IDENTIFICADOR_MIN: 4,
  USUARIO_IDENTIFICADOR_MAX: 30,
  USUARIO_NOMBRE_MIN: 2,
  USUARIO_NOMBRE_MAX: 50,
  USUARIO_EMAIL_MIN: 6,
  USUARIO_EMAIL_MAX: 50,
  USUARIO_CONTACTO_MIN: 10,
  USUARIO_CONTACTO_MAX: 15,
} as const;
